Remove mono from path for the msbuild test.
This test fails on M1 ARM machines hosted by GH
because the presence of mono confuses the restore mechanism.
We call dotnet msbuild on the M1 machines, but also need
a corresponding dotnet restore to be called.
However, with mono on the path, the test will call
nuget restore instead, and then dotnet msbuild
will not find the restored artifacts. Instead, it fails with
Error: [2023-11-14 12:11:05] [build-stdout] /Users/runner/.dotnet/sdk/7.0.403/Microsoft.Common.CurrentVersion.targets(1241,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [/Users/runner/work/semmle-code/semmle-code/target/codeql-csharp-integration-tests/ql/csharp/ql/integration-tests/all-platforms/msbuild/test.csproj]